'use client'

import Link from 'next/link'
import Image from 'next/image'
import { useEffect,useState } from 'react'
import ProductCard from '@/app/components/ProductCard'
import styles from './home.module.css'

type Product={id:string;stockNumber:string;name:string;brand?:string|null;condition:string;cpu?:string|null;ram?:string|null;storage?:string|null;sellingPrice:number;retailPrice?:number|null;warranty?:string|null;quantity:number;images:{url:string}[]}
const categories=[['01','Business laptops','Commercial-grade machines built for work.','/shop?category=Business%20Notebooks'],['02','Gaming','Serious performance without the retail markup.','/shop?category=Gaming%20Laptops'],['03','Apple','MacBooks and Apple technology, checked and backed.','/shop?category=Apple%20Products'],['04','Desktops','Office, home and high-performance systems.','/shop?category=Desktop%20Computers']]
export default function Home(){
 const [products,setProducts]=useState<Product[]>([]); const [loading,setLoading]=useState(true)
 useEffect(()=>{fetch('/api/products?take=6').then(r=>r.ok?r.json():[]).then(d=>setProducts(Array.isArray(d)?d:[])).catch(()=>setProducts([])).finally(()=>setLoading(false))},[])
 return <main className={styles.home}>
  <section className={`${styles.wrap} ${styles.hero}`}><div><div className={styles.eyebrow}>SOUTH AFRICAN COMPUTER RETAILER</div><h1>Quality tech.<br/><em>Without the retail price.</em></h1><p className={styles.lead}>New, demo and pre-owned laptops, desktops and technology at a fraction of retail prices. Every sale comes with warranty.</p><div className={styles.actions}><Link href="/shop" className={`${styles.button} ${styles.dark}`}>Shop products →</Link><Link href="/help-me-choose" className={`${styles.button} ${styles.quiet}`}>Help me choose</Link></div><div className={styles.trust}><div><span className={styles.stars}>★★★★★</span><strong>5.0</strong><span>Google rating</span></div><span className={styles.divider}/><div><strong>10+</strong><span>Years in business</span></div><span className={styles.divider}/><div><strong>SA</strong><span>FREE Nationwide Shipping</span></div></div></div><div className={styles.heroImage}><Image src="/sunder-store-hero.jpg" alt="Sunder Computers store" fill priority sizes="(max-width:900px) 100vw,50vw"/><div className={styles.overlay}/><div className={`${styles.label} ${styles.top}`}><span>VISIT OUR STORE</span><strong>Real products. In person.</strong></div><div className={`${styles.label} ${styles.bottom}`}><span>NEW · DEMO · PRE-OWNED</span><strong>Warranty backed</strong><small>FREE Nationwide Shipping</small></div></div></section>
  <section className={styles.reasons}><div className={`${styles.wrap} ${styles.reasonGrid}`}><div className={styles.reason}><strong>FRACTION OF RETAIL</strong><span>Quality technology at prices designed to make sense.</span></div><div className={styles.reason}><strong>WARRANTY ON ALL SALES</strong><span>Buy with confidence, whether new, demo or pre-owned.</span></div><div className={styles.reason}><strong>LIMITED STOCK</strong><span>Many units are individually sourced.</span></div><div className={styles.reason}><strong>REAL STORE IN BELLVILLE</strong><span>Visit us in Cape Town, browse or collect.</span></div></div></section>
  <section className={`${styles.wrap} ${styles.section}`}><div className={styles.sectionHead}><div><div className={styles.eyebrow}>HOT DEALS</div><h2>Limited stock. <em>Serious savings.</em></h2></div><Link className={styles.viewAll} href="/shop">View all products →</Link></div>{loading?<div className={styles.products}>{[1,2,3,4].map(i=><div key={i}/>)}</div>:<div className={styles.products}>{products.slice(0,4).map(p=><ProductCard key={p.id} product={p} compact/>)}</div>}</section>
  <section id="finder" className={`${styles.wrap} ${styles.finder}`}><div><div className={styles.eyebrow}>NOT SURE WHAT YOU NEED?</div><h2>Tell us what you're <em>buying it for.</em></h2><p>We'll make it easier to narrow down the right laptop without drowning you in specifications.</p><Link href="/shop" className={`${styles.button} ${styles.dark}`}>Help me choose →</Link></div><div className={styles.options}>{['Business','Study','Gaming','Creative','Home'].map((x,i)=><div className={styles.option} key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></section>
  <section className={styles.why}><div className={`${styles.wrap} ${styles.whyGrid}`}><div><div className={styles.eyebrow}>WHY SUNDER</div><h2>Real products.<br/>Real people.<br/><em>Real value.</em></h2></div><div><p className={styles.large}>We are a family-owned South African computer business focused on quality technology without unnecessary retail pricing.</p><div className={styles.features}>{[['01','Tested before sale','We inspect and test our equipment before it reaches a customer.'],['02','Warranty backed','Our products are sold with warranty.'],['03','Expert advice','Talk to people who actually work with the hardware.']].map(([n,t,p])=><div className={styles.feature} key={n}><strong>{n}</strong><div><h3>{t}</h3><p>{p}</p></div></div>)}</div></div></div></section>
  <section className={`${styles.wrap} ${styles.reviews}`}><div className={styles.eyebrow}>GOOGLE REVIEWS</div><h2>Real customers. <em>5-star rating.</em></h2><div className={styles.reviewBox}><div className={styles.rating}><h3>EXCELLENT</h3><div className={styles.stars}>★★★★★</div><p>5-Star Rating<br/>Based on 73 reviews</p></div><div className={styles.reviewCards}><article className={styles.review}><strong>Lizelle Heins</strong><div className={styles.stars}>★★★★★</div><p>“Fantastic service. Their pre-owned laptops are as good as new. Have just made my second purchase...”</p></article><article className={styles.review}><strong>Humble Beginning</strong><div className={styles.stars}>★★★★★</div><p>“Great service and very good products. Highly recommended for anyone looking for value.”</p></article></div></div></section>
  <section className={`${styles.wrap} ${styles.footerCta}`}><div><h2>Need help choosing?</h2><p>Talk to Sunder Computers in Bellville or browse the current stock online.</p></div><Link href="https://wa.me/27610571714">WhatsApp us</Link></section>
 </main>
}
