'use client'

import { useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import ProductCard from '@/app/components/ProductCard'
import styles from './shop.module.css'

type Product={id:string;stockNumber:string;name:string;brand:string;condition:string;cpu?:string|null;ram?:string|null;storage?:string|null;sellingPrice:number;salePrice?:number|null;retailPrice?:number|null;warranty?:string|null;quantity:number;images:{url:string}[]}
const categories=['Laptops','Desktops','Components','Gadgets']; const conditions=['New','Demo','Pre-owned','Refurbished']; const ramOptions=['4GB','8GB','12GB','16GB','24GB','32GB','64GB']; const storageOptions=['128GB','256GB','512GB','1TB','2TB','4TB']
export default function ShopPage(){
 const [products,setProducts]=useState<Product[]>([]),[q,setQ]=useState(''),[category,setCategory]=useState(''),[condition,setCondition]=useState(''),[brand,setBrand]=useState(''),[ram,setRam]=useState(''),[storage,setStorage]=useState(''),[sort,setSort]=useState('newest'),[saleOnly,setSaleOnly]=useState(false),[loading,setLoading]=useState(true)
 useEffect(()=>{const p=new URLSearchParams(location.search);setCategory(p.get('category')||'');setCondition(p.get('condition')||'');setQ(p.get('q')||'');setSaleOnly(p.get('onSale')==='true')},[])
 const brands=useMemo(()=>Array.from(new Set(products.map(p=>p.brand).filter(Boolean))).sort(),[products])
 useEffect(()=>{const c=new AbortController();const t=setTimeout(async()=>{setLoading(true);try{const p=new URLSearchParams({take:'100'});if(q)p.set('q',q);if(category)p.set('category',category);if(condition)p.set('condition',condition);if(brand)p.set('brand',brand);if(ram)p.set('ram',ram);if(storage)p.set('storage',storage);p.set('sort',sort);const r=await fetch(`/api/products?${p}`,{signal:c.signal});const data=r.ok?await r.json():[];setProducts(saleOnly?data.filter((p:Product)=>Number(p.salePrice||0)>0&&Number(p.salePrice)<Number(p.sellingPrice||0)):data)}catch(e){if((e as Error).name!=='AbortError')setProducts([])}finally{setLoading(false)}},120);return()=>{clearTimeout(t);c.abort()}},[q,category,condition,brand,ram,storage,sort,saleOnly])
 const clear=()=>{setQ('');setCategory('');setCondition('');setBrand('');setRam('');setStorage('');setSort('newest')}
 const title=q?`Search results for “${q}”`:saleOnly?'On sale':category|| (condition?`${condition} products`:'Shop all products')
 return <main className={styles.page}><section className={styles.hero}><div className={styles.heroInner}><div className={styles.eyebrow}>SUNDER COMPUTERS • ONLINE STORE</div><h1>Find your next<br/><span>great deal.</span></h1><p>New, demo and pre-owned technology, backed by warranty and real local support.</p><div className={styles.search}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search laptops, desktops, Apple and more..."/></div></div></section><section className={styles.shell}><aside className={styles.filters}><div className={styles.filterHead}><span className={styles.filterTitle}>FILTER PRODUCTS</span><button className={styles.clear} onClick={clear}>Clear all</button></div><FilterGroup title="CATEGORY"> <FilterButton active={!category} onClick={()=>setCategory('')}>All products</FilterButton>{categories.map(c=><FilterButton key={c} active={category===c} onClick={()=>setCategory(category===c?'':c)}>{c}</FilterButton>)}</FilterGroup><FilterGroup title="CONDITION">{conditions.map(c=><FilterButton key={c} active={condition===c} onClick={()=>setCondition(condition===c?'':c)}>{c}</FilterButton>)}</FilterGroup><FilterGroup title="BRAND"><select className={styles.select} value={brand} onChange={e=>setBrand(e.target.value)}><option value="">All brands</option>{brands.map(b=><option key={b}>{b}</option>)}</select></FilterGroup><FilterGroup title="RAM"><select className={styles.select} value={ram} onChange={e=>setRam(e.target.value)}><option value="">Any RAM</option>{ramOptions.map(x=><option key={x}>{x}</option>)}</select></FilterGroup><FilterGroup title="STORAGE"><select className={styles.select} value={storage} onChange={e=>setStorage(e.target.value)}><option value="">Any storage</option>{storageOptions.map(x=><option key={x}>{x}</option>)}</select></FilterGroup></aside><section><div className={styles.resultsHead}><div><div className={styles.eyebrow}>IN STOCK NOW</div><h2>{title}</h2></div><div className={styles.tools}><span className={styles.count}>{loading?'Loading…':`${products.length} products`}</span><select className={styles.sort} value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="priceAsc">Price: Low to High</option><option value="priceDesc">Price: High to Low</option><option value="name">Name A–Z</option></select></div></div>{loading?<div className={styles.grid}>{Array.from({length:8}).map((_,i)=><div className={styles.skeleton} key={i}/>)}</div>:products.length?<div className={styles.grid}>{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className={styles.empty}><strong>No products found.</strong><p>Try another search or clear the filters.</p><button onClick={clear}>Clear filters</button></div>}</section></section></main>
}
function FilterGroup({title,children}:{title:string;children:React.ReactNode}){return <div className={styles.group}><div className={styles.groupTitle}>{title}</div>{children}</div>}
function FilterButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button className={`${styles.filterButton} ${active?styles.active:''}`} onClick={onClick}>{children}</button>}
